# ColinConwell/base-notebook for deep learning
#
# sudo docker build -t cocoflow/mlworkspace:latest https://github.com/ColinConwell/notebooks.git#master:ubuntu16.04/gpu/cuda10.0-cudnn7/mlworkspace-notebook
#
#https://github.com/ml-tooling/ml-workspace/

FROM mltooling/ml-workspace-gpu:latest

# insert steps for single user notebook below
